### ISSUE TITLE
update tmp type definitions to 0.1.0

### ISSUE THREAD

**Issue by ViceIce** [benjamingr/tmp-promise#31] opened 2019-05-16 19:28 UTC
Please update the type definitions to `@types/tmp` 0.1.0, otherwise we will get wrong typings and missing `Options` and `SimpleOptions`.

**Comment by paulmelnikow** [comment] 2019-05-16 19:37
Hi! That was fixed in #27 after 1.1.0 was released and shipped in 2.0.0. However 2.0.0 was unpublished due to a regression (see #29). Hopefully it will be released again soon!

**Comment by benjamingr** [comment] 2019-05-21 11:44
This is now closed with 2.0.1 :]

**Closed by benjamingr** 2019-05-21 11:44 UTC

**Comment by ViceIce** [comment] 2019-05-21 11:58
Maybe we should add `@types/tmp` as a peerDependency?

**Comment by paulmelnikow** [comment] 2019-05-21 12:26
Probably it should be a dependency.

**Comment by benjamingr** [comment] 2019-05-21 12:30
Yeah that sounds like a good idea. PR welcome.

**Comment by ViceIce** [comment] 2019-05-21 12:32
I wond add it as dependency, because it is only required if you use typescript. and you only would need it as a dev dependency

**Comment by benjamingr** [comment] 2019-05-21 12:34
> you only would need it as a dev dependency

Since tmp doesn't maintain its own types (right?) I think the reasonable thing to do would be to publish @types/tmp-promise that would rely on @types/tmp as a dependency and then people could install that as a devDependency.

**Comment by ViceIce** [comment] 2019-05-21 12:39
the best would be to integrate the `@types/tmp` to `tmp` package

**Comment by benjamingr** [comment] 2019-05-21 12:43
> the best would be to integrate the @types/tmp to tmp package

@silkentrance what do you think?

**Comment by paulmelnikow** [comment] 2019-05-21 13:39
> Since tmp doesn't maintain its own types (right?) I think the reasonable thing to do would be to publish @types/tmp-promise that would rely on @types/tmp as a dependency and then people could install that as a devDependency.

Hmm, that would mean we'd stop publishing the types ourselves. It is easier to keep the definitions up to date (as we're now type-checking them) if we maintain them in this repoo publish them as part of our own package. The @types namespace is maintained through [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

> and you only would need it as a dev dependency

That's not true. If you use `tmp-promise` as a dev dependency, then you need @types/tmp as a dev dependency. If you use `tmp-promise` as a prod dependency, then @types/tmp also needs to be a prod dependency.

> the best would be to integrate the `@types/tmp` to `tmp` package

That's a nice idea. I'd happy to make a PR to do that.

**Comment by benjamingr** [comment] 2019-05-22 14:50
> then @types/tmp also needs to be a prod dependency.

Why? You mean if you're shipping typescript to production and compiling on your production server?

**Comment by ViceIce** [comment] 2019-05-23 04:11
Normally nobody needs them for production

**Comment by paulmelnikow** [comment] 2019-05-26 15:35
Ah yes, I see. Declaring it as a dependency allows us to trigger it to be installed automatically and match the version number. Making it a dev dependency of tmp-promise wouldn't work because dev dependencies wouldn't be installed. Making it a peer dependency would be no better, as it would yield warnings for non-TypeScript users. We could make it an optional dependency, though the consumer will still need to match the version on their own.

Until the types are shipped by `tmp` I'd still advocate making it a dependency, as it's the least error prone.

**Comment by benjamingr** [comment] 2019-05-26 15:44
> Until the types are shipped by tmp I'd still advocate making it a dependency, as it's the least error prone.

This means users' production environments are at-risk because of a devDependency which I am not a fan of (imagine a faulty postinstall script for example). 

Honestly I think I'm fine with the status quo with the better alternative being tmp including its types which I think they're open to.

**Comment by paulmelnikow** [comment] 2019-05-27 19:11
> This means users' production environments are at-risk because of a devDependency which I am not a fan of (imagine a faulty postinstall script for example).

While I appreciate this concern, for what it's worth the packages that come from DefinitelyTyped are very reputable, published through an automation chain which is far removed from individual bad actors. I don't think it is possible even through a PR review process to inject scripts into those packages.
